language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx


notifications:
  irc:
    nick: utime
    channels:
      - irc.uriirc.org:16667#hyeon
    template:
      - "#%{build_number} %{result}, %{build_url}"
    skip_join: true
