language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

cache:
  directories:
    - ~/.cargo
    - target

# IRC notification
notifications:
  irc:
    nick: utime
    channels: 'ircs://irc.uriirc.org:16664#hyeon'
    template: '#%{build_number} %{result}, %{build_url}'
    skip_join: true
